{
 "title": "mainflux",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Allocated Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{}",
     "legendFormat": "{{instance}} - Code {{code}}"
    }
   ]
  },
  {
   "title": "Goroutines instaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "go_goroutines{}", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}