File = "config.toml"

[channels]
  control = "05ff7d0b-62be-433a-9eff-cd963b4c6b5d"
  data = "b4be2125-a8fb-4da0-8d96-383605edb190"

[edgex]
  url = "http://localhost:48090/api/v1/"

[heartbeat]
  interval = "30s"

[log]
  level = "debug"

[mqtt]
  ca_cert = "PEM CA cert"
  ca_path = ""
  cert_path = ""
  client_cert = "PEM cert"
  client_key = "PEM client cert key"
  mtls = false
  password = "7c655598-38bf-46de-abba-f1b377461a44"
  priv_key_path = ""
  qos = 0
  retain = false
  skip_tls_ver = true
  url = "tcp://mqtt-adapter:1883"
  username = "bff01a80-a16d-4828-abe2-30e8f3f27b83"

[server]
  nats_url = "broker:4222"
  port = "9000"

[terminal]
  session_timeout = "30s"
